2장. 사이킷런으로 시작하는 머신러닝

#2-1. 사이킷런의 특징
* 파이썬 기반의 다른 머신러닝 패키지도 사이킷런 스타일의 API를 지향할 정도로 쉽고 가장 파이썬스러운 API를 제공함
* 머신러닝을 위한 매우 다양한 알고리즘과 개발을 위한 편리한 프레임워크와 API를 제공함
* 오랜기간 실전 환경에서 검증됐으며, 매우 많은 환경에서 사용하는 성숙한 라이브러리

#2-2. 첫번째 머신러닝 만들어 보기- 붓꽃 품종 예측하기
* 분류: 대표적인 지도학습 방법
* 지도학습: 학습을 위한 다양한 피처와 분류 결정값인 레이블 데이터로 모델을 학습한 뒤, 별도의 테스트 데이터 세트에서 미지의 레이블을 예측함
  + 학습 데이터 세트: 학습을 위해 주어진 데이터 세트
  + 테스트 데이터 세트: 머신러닝 모델의 예측 성능을 평가하기 위해 별도로 주어진 데이터 세트
* 사이킷런 패키지 내의 모듈명은 sklearn으로 시작하는 명명 규칙이 있음
* sklearn.datasets 내의 모듈: 사이킷런에서 자체적으로 제공하는 데이터 세트를 생성하는 모듈의 모임
* sklearn.tree 내의 모듈은 트리 기반 ML 알고리즘을 구현한 클래스의 모임
* sklearn.model_selection: 학습 데이터, 검증 데이터, 예측 데이터로 데이터를 분리하거나 최적의 하이퍼 파라미터로 평가하기 위한 다양한 모듈의 모임
  + 하이퍼 파라미터: 머신러닝 알고리즘별로 최적의 학습을 위해 직접 입력하는 파라미터들, 머신러닝 알고리즘의 성능을 튜닝할 수 있음
* train_test_split(): 데이터 세트를 학습 데이터와 테스트 데이터로 분리

In [4]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier  #의사결정트리 알고리즘을 활용함
from sklearn.model_selection import train_test_split  #학습데이터와 테스트데이터로 분리

In [5]:
import pandas as pd

#붓꽃 데이터 세트를 로딩함
iris=load_iris()

#iris.data는 Iris 세트에서 피처(feature)만으로 된 데이터를 numpy로 가지고 있음
iris_data=iris.data

# iris.target은 붓꽃 데이터 세트에서 레이블(결정 값) 대이터를 numpy로 가지고 있음
iris_label=iris.target
print('iris target 값:', iris_label)
print('iris target 명:', iris.target_names)

# 붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환함
iris_df=pd.DataFrame(data=iris_data,columns=iris.feature_names)
iris_df['label']=iris.target  #iris_df라는 데이터프레임에 'label'이라는 새로운 열(column)을 만들고, 그 열에 iris.target 배열의 값들을 순서대로 할당함
iris_df.head(3)


iris target 값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

* 학습용 데이터와 테스트용 데이터를 분리함
  + train_test_split(): 학습 데이터와 테스트 데이터를 test_size 파라미터 입력값의 비율로 쉽게 분할함
  + random_state: 호출할 때마다 같은 학습/테스트 용 데이터 세트를 생성하기 위해 주어지는 난수 발생 값
    - 이를 지정하지 않으면, 수행할 때마다 다른 학습/테스트 용 데이터를 만들 수 있음
    - 숫자ㅏ 자체는 어떤 값을 지정해도 상관 X

In [6]:
X_train, X_test, y_train, y_test = train_test_split(iris_data,iris_label,test_size=0.2, random_state=11)

* 이 데이터를 기반으로 머신러닝 분류 알고리즘의 하나인 의사 결정 트리를 이용해 학습과 예측 수행
  + 사이킷런의 의사 결정 트리 클래스인 DecisionTreeClassifier를 객체로 생성
  + 생성된 DecisionTreeClassifier 객체의 fit()에 학습용 피처 데이터 속성과 결정값 데이터 세트를 입력해 호출하면 학습이 수행됨

In [7]:
# DecisionTreeClassifier 객체 생성
dt_clf=DecisionTreeClassifier(random_state=11)

#학습수행
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

  + DecisionTreeClassifier 객체의 predict()에 테스트용 피처 데이터 세트를 입력해 호출하면 학습된 모델 기반에서 테스트 데이터 세트에 대한 예측값을 반환함

In [8]:
pred=dt_clf.predict(X_test)

* 예측 결과를 기반으로 의사 결정 트리 기반의 DecisionTreeClassifier의 예측 성능 평가
  + accuracy_score(실제 레이블 데이터 세트, 예측 레이블 데이터 세트): 정확도를 측정함

In [9]:
from sklearn.metrics import accuracy_score
print('예측 정확도:{0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도:0.9333


* 프로세스
  + 1. 데이터 세트 분리: 데이터를 학습 데이터와 테스트 데이터로 분리함
  + 2. 모델 학습: 학습 데이터를 기반으로 ML 알고리즘을 적용해 모델을 학습시킴
  + 3. 예측 수행: 학습된 ML 모델을 이용해 테슽 데이터의 분류를 예측함
  + 4. 평가: 예측된 결과값과 테스트 데이터의 실제 결괏값을 비교해 ML 모델 성능을 평가함

#2-3. 사이킷런의 기반 프레임워크 익히기

## 2-3-1. Estimator 이해 및 fit(), predict()
* 사이킷런은 ML 모델 학습을 위해서 fit()을, 학습된 모델의 예측을 위해 predict()를 제공함
* 분류, 회귀의 다양한 알고리즘을 우현한 모든 사이킷런 클래스는 fit(), predict()만을 이용해 간단하게 학습과 예측 결과를 반환함
* Estimator: Classifier와 Regressor를 합친 것, 즉 지도학습의 모든 알고리즘을 구현한 클래스를 통칭함
  + Clssifier: 분류 알고리즘을 구현한 클래스
  + Estimator: 회귀 알고리즘을 구현한 클래스
* cross_val_score()와 같은 evaluation 함수, GridSearchCV와 같은 하이퍼 파라미터 튜닝을 지원하는 클래스의 경우 이 Estimator를 인자로 받음
* 인자로 받은 Estimator에 대해서 cross_val_score(), GridSearchCV.fit() 함수 내에서 이 Estimator의 fit()과 predict()를 호출해서 평가를 받거나 하이퍼 파라미터 튜닝을 수행함
* 비지도학습인 차원 축소, 클러스터링, 피처 추출 등을 구현한 클래스 역시 대부분 fit(), transform()을 적용함
  + fit(): 입력 데이터의 형태에 맞춰 데이터를 변환하기 위한 사전 구조를 맞추는 작업
  + transform(): 이후 입력 데이터의 차원 변환, 클러스터링, 피처 추출 등의 실제 작업 수행

 ## 2-3-2. 사이킷런의 주요 모듈
  * 머신러닝 모델을 구축하는 주요 프로세스: 피처의 가공, 변경, 추출을 수행하는 피처 처리, ML 알고리즘 학습/예측 수행, 모델 평가의 단계를 반복적으로 수행
  * 사이킷런 패키지는 머신러닝 모델을 구축하는 주요 프로세스를 지원하기 위해 매우 편리하고, 다양하며, 유연한 모듈을 제공

  ## 2-3-3. 내장된 예제 데이터 세트
  * 사이킷런에 내장 되어 있는 데이터 세트
    + 분류나 회귀를 연습하기 위한 예제용도의 데이터 세트
    + 분류나 클러스터링을 위해 표본 데이터로 생성될 수 있는 데이터 세트
  * fetch 계열의 명령: 데이터의 크기가 커서 패키지에 처음부터 저장되어 있지 않고 인터넷에서 내려받아 홈 디렉터리 아래의 scikit_learn_data라는 서브 디렉터리에 저장한 후 추후 불러들이는 데이터
  * 분류와 클러스터링을 위한 표본 데이터 생성기
    + datasets.make_classification()
      - 분류를 위한 데이터 세트를 만듦
      - 특히 높은 상관도, 불필요한 속성 등의 노이즈 효과를 위한 데이터를 무작위로 생성해줌
    + datasets.make_blobs()
      - 클러스터링을 위한 데이터 세트를 무작위로 생성해줌
      - 군집 지정 개수에 따라 여러 가지 클러스터링을 위한 데이터 세트를 쉽게 만들어줌
* 분류나 회귀를 위한 연습용 예제 데이터는 일반적으로 딕셔너리 형태
* 키는 보통 data, target, target_names, feature_names, DESCR로 구성돼 있음
  + data: 피처의 데이터 세트
  + target: 분류 시 레이블 값, 회귀 시 숫자 결괏값 데이터 세트
  + target_names: 개별 레이블의 이름
  + feature_names: 피처의 이름
  + DESCR: 데이터 세트에 대한 설명과 각 피처의 설명
* data,target: 넘파이 배열 타입 / target_names, feature_names: 넘파이 배열 또는 파이썬 리스트 타입 / DESCR: 스트링 타입
* 피처의 데이터 값을 반환받기 위해서는 내장 데이터 세트 API를 호출한 뒤 그 Key값을 지정하면 됨
* Bunch 클래스는 파이썬 딕셔너리 자료형과 유사함

In [10]:
from sklearn.datasets import load_diabetes
iris_data=load_iris()
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


* 데이터 키: 피처들의 데이터 값
* 데이터 세트가 딕셔너리 형태이기 때문에 피처 데이터 값을 추출하기 위해서는 '데이터 세트.data' 혹은 '데이터 세트['data']'를 이용하면 됨

In [11]:
print('|n feature_names의 type:', type(iris_data.feature_names))
print('feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('|n target_names의 type:', type(iris_data.target_names))
print('target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('|n data의 type:', type(iris_data.data))
print('data의 shape:', len(iris_data.data))
print(iris_data['data'])

print('|n target의 type:', type(iris_data.target))
print('target의 shape:', len(iris_data.target))
print(iris_data.target)

|n feature_names의 type: <class 'list'>
feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
|n target_names의 type: <class 'numpy.ndarray'>
target_names의 shape: 3
['setosa' 'versicolor' 'virginica']
|n data의 type: <class 'numpy.ndarray'>
data의 shape: 150
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.

#2-4. Model Selection 모듈 소개
: model_selection 모듈은 학습 데이터와 테스트 데이터 세트를 분리하거나 교차 검증 분할 및 평가, 그리고 Estimator의 하이퍼 파라미터를 튜닝하기 위한 다양한 함수와 클래스를 제공함

##2-4-1. 학습/테스트 데이터 세트 분리 - train_test_split()
* 학습과 예측을 동일한 데이터 세트로 수행한 결과

In [12]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
df_clf=DecisionTreeClassifier()
train_data=iris.data
train_label=iris.target
dt_clf.fit(train_data,train_label)  #모델을 학습시키는 과정

#학습 데이터 세트로 예측 수행
pred= dt_clf.predict(train_data)
print('예측 정확도:',accuracy_score(train_label,pred))

예측 정확도: 1.0


* train_test_split(피처 데이터 세트, 레이블 데이터 세트, ...): 선택적으로 다음 파라미터들을 입력 받음
  + test_size: 전체 데이터에서 테스트 데이터 세트 크기를 얼마나 샘플링할 것인지, 디폴트는 0.25
  + train_size: 전체 데이터에서 학습용 데이터 세트 크기를 얼마로 샘플링할 것인지, 잘 사용되지 않음
  + shuffle: 데이터를 분리하기 전에 데이터를 미리 섞을지, 디폴트는 True, 데이터를 분산시켜 좀 더 효율적인 학습 및 테스트 데이터 세트를 만드는 데 사용됨
  + random_state: 호출할 때마다 동일 학습/테스트용 데이터 세트를 생성하기 위해 주어지는 난수 값, 지정하지 않으면 수행할 때마다 다른 학습/테스트용 데이터를 생성함
  + train_test_split()의 반환값은 튜플 형태임. 순차적으로 학습용 데이터의 피처 데이터 세트, 테스트용 데이터의 피처 데이터 세트, 학습룔 데이터의 레이블 데이터 세트, 테스트용 데이터의 레이블 데이터 세트가 반환됨


In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf=DecisionTreeClassifier()
iris_data=load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

In [14]:
dt_clf.fit(X_train,y_train)
pred=dt_clf.predict(X_test)
print('예측정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측정확도: 0.9556


* 학습을 위한 데이터의 양을 일정 수준 이상으로 보장하는 것도 중요하지만, 학습된 모델에 대해 다양한 데이터를 기반으로 예측 성능을 평가해보는 것도 매우 중요함

## 2-4-2. 교차 검증
* 알고리즘을 학습시키는 학습 데이터와 이에 대한 예측 성증을 평가하기 위한 별도의 테스트용 데이터를 마련하는 것은 과적합이라는 약점을 가질 수 있음
* 과적합: 모델이 학습 데이터에만 과도하게 최적화되어, 실제 예측을 다른 데이터로 수행할 경우에는 예측 성능이 과도하게 떨어짐
* 과적합 문제를 개선하기 위해 교차 검증을 이용
* 교차 검증: 데이터 편중으 ㄹ막기 위해 별도의 여러 세트로 구성된 학습 데이터 세트와 검증 데이터 세트에서 학습과 평가를 수행함
  + 각 세트에서 수행한 평가 결과에 따라 하이퍼 파라미터 튜닝 등의 모델 최적화를 더욱 손수비게 할 수 있음
* 대부분의 ML 모델의 성능 평가는 교차 검증 기반으로 1차 평가를 한 뒤에 최종적으로 테스트 데이터 세트에 적용해 평가하는 프로세스
* 학습, 검증, 테스트 데이터 세트: 학습데이터를 분할하여 학습 데이터와 학습된 모델의 성능을 일차 평가하는 검증 데이터로 나눔

### K 폴드 교차 검증
: K개의 폴드된 데이터 세트를 학습과 검증을 위한 데이터 세트로 변경하면서 K번의 평가를 수행한 뒤, 이 K개의 평가를 평균한 결과를 가지고 예측 성능을 평가함

* KFold 클래스 이용

In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)

kfold=KFold(n_splits=5)  #5개의 폴드 세트로 분리
cv_accuracy=[]  #폴드 세트별 정확도를 담을 리스트 객체 생성
print('붓꽃 데이터 세트 크기:',features.shape[0])

붓꽃 데이터 세트 크기: 150


* 생성된 KFold 객체의 split()을 호출해 전체 붓꽃 데이터를 5개의 폴드 데이터 세트로 분리
* KFold 객체는 split()을 호출하면 학습용/검증용 데이터로 분할할 수 있는 인덱스를 반환함 => 학습/검증용 데이터 추출은 반환된 인덱스를 기반으로 개발 코드에서 직접 수행해야 함

In [16]:
n_iter=0  #n_iter라는 변수를 만들고, 그 값을 0으로 설정함. 이는 반복문이 시작되기 전에 "반복 횟수가 0"이라고 알려줌


#KFold 객체의 split()를 호출하면 폴드별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features): #kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test=features[train_index],features[test_index]
  y_train, y_test=label[train_index],label[test_index]
  #학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred=dt_clf.predict(X_test)
  n_iter+=1  # n_iter = n_iter + 1과 같음. for 루프가 한 번 실행될 때마다 n_iter의 값이 1씩 늘어남. 이 변수는 현재 몇 번째 교차 검증(cross-validation)이 진행 중인지 추적하는 카운터 역할을 함.
  #반복 시마다 정확도 측정
  accuracy=np.round(accuracy_score(y_test,pred),4)
  train_size=X_train.shape[0]  #학습용 데이터의 행의 개수를 셈으로써 학습용 데이터의 개수를 알 수 있음
  test_size=X_test.shape[0]  #검증용 데이터의 행의 개수를 셈으로써 검증용 데이터의 개수를 알 수 있음
  print('\n#{0} 교차 검증 정확도:{1}, 학습데이터 크기: {2}, 검증 데이터 크기:{3}'.format(n_iter,accuracy,train_size, test_size))
  print('\n#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
  cv_accuracy.append(accuracy)  #.append(): 파이썬 리스트의 메서드로, 괄호 안의 값을 리스트의 맨 뒤에 추가함

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도:1.0, 학습데이터 크기: 120, 검증 데이터 크기:30

#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도:0.9667, 학습데이터 크기: 120, 검증 데이터 크기:30

#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도:0.8667, 학습데이터 크기: 120, 검증 데이터 크기:30

#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도:0.9333, 학습데이터 크기: 120, 검증 데이터 크기:30

#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도:0.7333, 학습데이터 크기: 120, 검증 데이터 크기:30

#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


###Stratified K 폴드
: 불균형한 분포도를 가진 레이블(특정 레이블 값이 특이하게 많거나 매우 적어서 값의 분포가 한 쪽으로 치우치는 것) 데이터 집합을 위한 K 폴드 방식
* 원본 데이터의 레이블 분포를 먼저 고려한 뒤 이 분포와 동일하게 학습과 검증 데이터 세트를 분배함

In [17]:
import pandas as pd

iris=load_iris()
iris_df=pd.DataFrame(data=iris.data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [18]:
kfold=KFold(n_splits=3)
n_iter=0
for train_index,test_index in kfold.split(iris_df):
  n_iter +=1
  label_train=iris_df['label'].iloc[train_index]
  label_test=iris_df['label'].iloc[test_index]
  print('##교차 검증:{0}'.format(n_iter))
  print('학습 레이블 데이터 분포:|n',label_train.value_counts())
  print('검증 레이블 데이터 분포:|n',label_test.value_counts())

##교차 검증:1
학습 레이블 데이터 분포:|n label
1    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:|n label
0    50
Name: count, dtype: int64
##교차 검증:2
학습 레이블 데이터 분포:|n label
0    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:|n label
1    50
Name: count, dtype: int64
##교차 검증:3
학습 레이블 데이터 분포:|n label
0    50
1    50
Name: count, dtype: int64
검증 레이블 데이터 분포:|n label
2    50
Name: count, dtype: int64


### 교차 검증을 보다 간편하게 - cross_val_score()
creoss_val_score(estimator, X, y=None, cv=None, n_jobs=1, verbose=0, fit_patams=None, pre_dispatch='2*n_jobs')
* 주요 파라미터
  + estimator: 분류 알고리즘 클래스인 Classifier OR 회귀 알고리즘 클래스인 Regressor
    - Classifier: Stratified K 폴드 형식으로 레이블값의 분포에 따라 학습/테스트 세트를 분할함
    - Regressor: K 폴드 형식으로 분할
  + X: 피처 데이터 세트
  + y: 레이블 데이터 세트
  + scoring: 예측 성능 평가 지표
  + cv: 교차 검증 폴드 수
* 반환 값은 scoring 파라미터로 지정된 성능 지표 측정값을 배열 형태로 반환함

In [22]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data=load_iris()
dt_clf=DecisionTreeClassifier(random_state=156)

data=iris_data.data
label=iris_data.target

#성능 지표는 정확도(accuracy), 교차 검증 세트는 3개
scores=cross_val_score(dt_clf,data,label,scoring='accuracy',cv=3)
print('교차 검증별 정롹도:', np.round(scores,4))
print('평균 검증 정확도:', np.round(np.mean(scores),4))

교차 검증별 정롹도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


* cv로 지정된 횟수만큼, scoring 파라미터로 지정된 평가 지표로 평가 결괏값을 배열로 반환하고, 이를 일반적으로 평균해 평가 수치로 사용함
* 내부에서 Estimator를 학습, 예측 평가시켜주므로 간단하게 교차 검증을 수행함
* 내부적으로 SratifiedKFold를 이용하기 때문에 각 교차 검증별 정확도와 평균 검증 정확도가 cross_val_score() 수행 결과와 동일함
* cross_validate(): 여러 개의 평가 지표를 반환하고, 학습 데이터에 대한 성능 평가 지표와 수행 시간도 같이 제공함

##2-4-3. GridSearchCV - 교차 검증과 최적 하이퍼 파라미터 튜닝을 한 번에
* 하이퍼 파라미터: 머신러닝 알고리즘을 구성하는 주요 구성 요소이며, 이 값을 조정해 알고리즘의 예측 성능을 개선할 수 있음
* 사이킷런은 GridSearchCV API를 이용해 Classifier나 Regressor와 같은 알고리즘에 사용되는 하이퍼 파라미터를 순차적으로 입력하면서 편리하게 최적의 파라미터를 도출할 수 있는 방안을 제공함



In [23]:
grid_parameters={'max_depth':[1,2,3], 'min_samples_split':[2,3]}

* GridSearchCV는 교차 검증을 기반으로 하이퍼 파라미터의 최적 값을 찾게 해줌: 데이터 세트를 cross-validation을 위한 학습/테스트 세트로 자동으로 분할한 뒤에 하이퍼 파라미터 그리드에 기술된 모든 파라미터를 순차적으로 적용해 최적의 파라미터를 찾음
* 수행 시간이 상대적으로 오래 걸림
* 주요 파라미터
  + estimator: classifier, regressor, pipeline이 사용될 수 있음
  + param_grid: key + 리스트 값을 가지는 딕셔너리가 주어짐, estimator의 튜닝을 위해 파라미터명과 사용될 여러 파라미터 값을 지정함
  + scoring: 예측 성능을 측정할 평가 방법을 지정함, 보통 사이킷런의 성능 평가 지표를 지정하는 문자열(ex. 정확도의 경우 'accuracy')로 지정하나 별도의 성능 평가 지표 함수도 지정할 수 있음
  + cv: 교차 검증을 위해 분할되는 학습/테스트 세트의 개수
  + refit: 디폴트는 True, True로 생성 시 가장 최적의 하이퍼 파라미터를 찾은 뒤 입력된 estimator 객체를 해당 하이퍼 파라미터로 재학습시킴

In [25]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

#데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris_data=load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data,iris_data.target,test_size=0.2,random_state=121)
dtree=DecisionTreeClassifier()

#파라미터를 딕셔너리 형태로 설정
parameters={'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [27]:
import pandas as pd

#param_grid의 하이퍼 파라미터를 3개의 train,test set fold로 나누어 테스트 수행 설정
#refit=True가 디폴트임. True이면 가장 좋은 파라미터 설정으로 재학습시킴
#학습 데이터를 cv에 기술된 폴딩 세트로 분할해 param_grid에 기술죈 하이퍼파라미터를 순차적으로 변경하면서 학습/평가를 수행하고 그 결과를 cv_results_ 속성에 기록함
#cv_results_는 gridsearchcv의 결과 세트로서 딕셔너리 형태로 key 값과 리스트 형태의 value 값을 가짐
grid_dtree=GridSearchCV(dtree,param_grid=parameters, cv=3, refit=True)

#붓꽃 학습 데이터로 param_grid의 하이퍼파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train,y_train)

#GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

* rank_test_score: 하이퍼 파라미터별로 성능이 좋은 score 순위를 나타냄, 1위 가장 뛰어난 순위이며 이때의 파라미터가 최적의 하이퍼 파라미터임
* params 칼럼: 수행할 때마다 적용된 개별 하이퍼 파라미터값을 나타냄
* mean_test_score: 개별 하이퍼 파라미터별로 CV의 폴딩 테스트 세트에 대해 총 수행한 평가 평균값

* GridSearchCV 객체의 fit()을 수행하면 최고 성능을 나타낸 하이퍼 파라미터의 값과 그때의 평가 결과 값이 각각 best_params_, best_score_ 속성에 기록됨

In [28]:
print('GridSearchCV 최적 파라미터:',grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0;.4f}:',format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:{0;.4f}: 0.975


* GridSearchCV 객체의 생성 파라미터로 refit=True가 디폴트
* True이면 GridSearchCV가 최적 성능을 나타내는 하이퍼 파라미터로 Estimator를 학습해 best_estimator_로 저장함

In [29]:
#GridSearchCV의 refit으로 이미 학습된 estimator 변환
estimator=grid_dtree.best_estimator_

#GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred=estimator.predict(X_test)
print('테스트 데이터 세트 정확도:{0:.4f}'.format(accuracy_score(y_test,pred)))

테스트 데이터 세트 정확도:0.9667


* 일반적으로 학습 데이터를 GridSearchCV를 이용해 최적 하이퍼 파라미터 튜닝을 수행한 뒤에 별도의 테스트 데이터 세트에서 이를 평가하는 것이 일반적인 러신머닝 모델 적용방법임