# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [55]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [27]:
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [54]:
array_4 = np.array([1,2,3,4,5,6,7,8,9,10])
print(array_4.nbytes)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [53]:
null_vector_5 = np.zeros(10)
null_vector_5[4] = 1
print(null_vector_5)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [4]:
vector_values=np.arange(start=10, stop=50)
print(vector_values)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [6]:
vector_values_desc=np.arange(start=10, stop=50)[::-1]
print(vector_values_desc)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
matrix_8=np.arange(start=0, stop=9)
matrix_8_1=matrix_8.reshape(3,3)
print(matrix_8_1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [16]:
array_9=np.array([1,2,0,0,4,0])
array_9_1=array_9[array_9!=0]
array_9_2 = np.nonzero(array_9)[0]
print(array_9_2)

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [17]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [19]:
random_values = np.random.random((3, 3, 3))
print(random_values)

[[[0.95212059 0.81724688 0.84400058]
  [0.13829111 0.07395559 0.35115779]
  [0.35467213 0.33785428 0.48586685]]

 [[0.64820882 0.67950959 0.83201036]
  [0.73464708 0.9680743  0.39872373]
  [0.25991849 0.13676256 0.01950447]]

 [[0.38408384 0.64318158 0.13309075]
  [0.24262423 0.69593778 0.74367459]
  [0.45810046 0.40854587 0.11793223]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [23]:
random_values_2 = np.random.random((10,10))
print(random_values_2)
min=np.min(random_values_2)
print(min)
max=np.max(random_values_2)
print(max)

[[0.74667545 0.74505216 0.52388667 0.67188196 0.71800342 0.59345003
  0.67786835 0.97840939 0.53972937 0.76926583]
 [0.4861497  0.07240812 0.54209352 0.38596903 0.96906494 0.6767884
  0.13126162 0.19400365 0.96732269 0.03620515]
 [0.34397082 0.57858524 0.05869128 0.49958547 0.27455142 0.55216408
  0.00508836 0.65031802 0.87210148 0.99682549]
 [0.55583538 0.52099287 0.02639861 0.31653961 0.17450692 0.70326809
  0.04999814 0.01387667 0.21429303 0.37624603]
 [0.63774368 0.51852999 0.06726492 0.19259685 0.79082187 0.77833841
  0.70270657 0.40479494 0.32658799 0.58525349]
 [0.00653959 0.22566343 0.13517515 0.5347333  0.91130498 0.86976623
  0.89233002 0.73294818 0.25789465 0.43048923]
 [0.99791303 0.25270334 0.71150328 0.87116332 0.55682277 0.23691548
  0.12662163 0.91960721 0.82653598 0.81958057]
 [0.7305985  0.31469884 0.02490779 0.20021973 0.33298108 0.24353278
  0.055586   0.27291598 0.7651741  0.94122753]
 [0.49572362 0.61343932 0.09530429 0.46201652 0.80546762 0.16118649
  0.81873083 

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [25]:
random_vector_13 = np.random.random(30)
print(random_vector_13)
mean=np.mean(random_vector_13)
print(mean)

[0.57387124 0.53474642 0.77575859 0.09674818 0.79000904 0.51732366
 0.42024436 0.17731389 0.69974829 0.16746528 0.81368754 0.81215576
 0.53479907 0.30225685 0.43445247 0.06348563 0.17563518 0.16418086
 0.32682165 0.34408013 0.26631644 0.37646693 0.1164875  0.13029115
 0.90679528 0.05922254 0.75711015 0.33059725 0.46286361 0.56611556]
0.4232350174828892


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [43]:
array2d=np.ones((3,3),dtype='int32')
array2d[1,1]=0
print(array2d)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

* nan: 정의되지 않은 값은 어떤 연산을 해도 정의되지 않은 값
* false: nan은 자기 자신과도 같지 않음 (비교 연산 항상 false)
* false: nan과의 모든 비교는 False (<, >, == 전부 false)
* nan: nan끼리의 연산도 nan
* true: set은 해시를 이용해서 membership check를 하는데, NaN은 해싱할 수 있고 같은 객체로 인식될 수 있음
* true: 부동소수점 표현 오차 때문에 0.1은 2진수로 딱 떨어지지 않기 때문에 3*0.1은 0.30000000000000004로 저장됨 -> 0.3과 정확히 같지 않음

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [42]:
matrix_16=np.zeros((5,5),dtype='int32')
matrix_16[1,0]=1
matrix_16[2,1]=2
matrix_16[3,2]=3
matrix_16[4,3]=4
print(matrix_16)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [46]:
matrix_17=np.zeros((8,8),dtype='int32')
matrix_17[1::2,::2]=1
matrix_17[::2,1::2]=1
print(matrix_17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [47]:
index=np.unravel_index(100,(6,7,8))
print(index)

(np.int64(1), np.int64(5), np.int64(4))


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [48]:
randommatrix_19=np.random.random((5,5))
xbar=np.mean(randommatrix_19)
s=np.std(randommatrix_19)
Z=(randommatrix_19-xbar)/s
print(Z)


[[-1.37154199 -1.19390573  0.38993734 -0.69366683 -1.10152959]
 [ 0.84388894  1.10981782  0.01355184 -1.67605721 -1.05040744]
 [ 1.78680897 -0.63135443 -0.11478921  0.78593849  0.94312087]
 [ 1.04190453 -1.03181028 -0.81160948  1.51775698 -1.18428856]
 [ 0.28576852  1.18034451  0.6372061  -0.30119272  0.62610859]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [52]:
custom_dtype=np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
