In [1]:
import numpy as np

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [2]:
A=np.random.random((5,3))
B=np.random.random((3,2))
np.dot(A,B)

array([[0.86523413, 0.43870221],
       [0.31013975, 0.15149862],
       [0.38156   , 0.7203765 ],
       [0.59280554, 0.63527079],
       [0.75261787, 0.26944307]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [3]:
array=np.arange(10)
array[(3<array)&(array<8)]*=-1
print(array)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [4]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


두번째에서 -1은 axis=-1을 의미함.
axis=-1은 유일한 축(0번 축)을 가리킴.
그래서 그냥 단순히 모든 원소를 더하면 됨.

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [41]:
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[[        4 387420489         1]
 [ 16777216       256         1]
 [        4       256       256]]
[[  2 256   0]
 [128   8   0]
 [  2   8   8]]
[[False False False]
 [False False False]
 [False False False]]
[[0.+2.j 0.+9.j 0.+0.j]
 [0.+8.j 0.+4.j 0.+0.j]
 [0.+2.j 0.+4.j 0.+4.j]]
[[2. 9. 0.]
 [8. 4. 0.]
 [2. 4. 4.]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

* Z**Z 가능: 거듭제곱
* 2 << Z >> 2: 가능 shift
* Z <- Z: 가능
* 1j*Z: 가능 허수에 Z 곱한 것
* Z/1/1: 가능 float형 연산
* Z<Z>Z: 불가능

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [5]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipython-input-548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipython-input-548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipython-input-548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

* Nan: 나누기 불가
* 0: 넘파이에서 몫을 계산하는 // 연산자는 따로 정의되지 않은 연산에 대해 0을 반환함
* -9.22337204e+18: Nan이 float에서 int로 바뀌는 과정에서 특정 수로 반환됨,표현할 수 있는 최솟값으로 대체해 출력됨


<ipython-input-64-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-64-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-64-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [10]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 4 6 8 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [11]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipython-input-244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [12]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [42]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [19]:
arr=np.random.random(10)
int_part1=arr//1
print(arr)
print(int_part1)

int_part2=np.floor(arr)
print(arr)
print(int_part2)

[0.29883592 0.54821306 0.6766892  0.80880294 0.50850965 0.09694861
 0.50239062 0.8527845  0.33158262 0.95582149]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.29883592 0.54821306 0.6766892  0.80880294 0.50850965 0.09694861
 0.50239062 0.8527845  0.33158262 0.95582149]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [22]:
array31=np.zeros((5,5))
array31+=np.arange(5)
print(array31)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [23]:
vector_30=np.random.random(10)
vector_30.sort()
print(vector_30)

[0.23821072 0.44071943 0.56257793 0.58410137 0.64269738 0.79279708
 0.85510036 0.93111743 0.9548568  0.96211614]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [25]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal=np.array_equal(A,B)
print(equal)

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [27]:
Z = np.random.random((10,2))
x,y = Z[:,0], Z[:,1]
R = np.sqrt(x**2+y**2)
T = np.arctan2(y,x)
print(R)
print(T)

[0.86526713 0.98556309 0.52357732 0.81392813 0.42915296 1.01994348
 0.92800973 0.72487943 1.05859989 1.01474138]
[0.15892783 1.5490205  0.27394101 1.24034363 0.05101074 0.50452312
 1.29037587 1.07123208 0.64686413 1.25689764]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [33]:
Z = np.random.random(10)
Z[Z.argmax()]=0
print(Z)

[0.         0.15714658 0.73108354 0.8826748  0.6331042  0.56680446
 0.67993873 0.65150166 0.88145284 0.4339393 ]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [34]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(np.abs(Z-v))
print(np.abs(Z-v).argmin())

[97.7715855 96.7715855 95.7715855 94.7715855 93.7715855 92.7715855
 91.7715855 90.7715855 89.7715855 88.7715855 87.7715855 86.7715855
 85.7715855 84.7715855 83.7715855 82.7715855 81.7715855 80.7715855
 79.7715855 78.7715855 77.7715855 76.7715855 75.7715855 74.7715855
 73.7715855 72.7715855 71.7715855 70.7715855 69.7715855 68.7715855
 67.7715855 66.7715855 65.7715855 64.7715855 63.7715855 62.7715855
 61.7715855 60.7715855 59.7715855 58.7715855 57.7715855 56.7715855
 55.7715855 54.7715855 53.7715855 52.7715855 51.7715855 50.7715855
 49.7715855 48.7715855 47.7715855 46.7715855 45.7715855 44.7715855
 43.7715855 42.7715855 41.7715855 40.7715855 39.7715855 38.7715855
 37.7715855 36.7715855 35.7715855 34.7715855 33.7715855 32.7715855
 31.7715855 30.7715855 29.7715855 28.7715855 27.7715855 26.7715855
 25.7715855 24.7715855 23.7715855 22.7715855 21.7715855 20.7715855
 19.7715855 18.7715855 17.7715855 16.7715855 15.7715855 14.7715855
 13.7715855 12.7715855 11.7715855 10.7715855  9.7715855  8.771

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [35]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [36]:
n = 3
p = 2
Z = np.ones((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'8')
print(Z)

[[1. 8. 1.]
 [1. 1. 8.]
 [1. 1. 1.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [37]:
Z = np.random.randint(0,10,(3,3))

print(Z)
print(Z[Z[:,0].argsort()])

[[2 9 0]
 [8 4 0]
 [2 4 4]]
[[2 9 0]
 [2 4 4]
 [8 4 0]]


In [38]:
print(Z)
print(Z[Z[:,1].argsort()])

[[2 9 0]
 [8 4 0]
 [2 4 4]]
[[8 4 0]
 [2 4 4]
 [2 9 0]]


In [40]:
print(Z)
print(Z[Z[:,2].argsort()])

[[2 9 0]
 [8 4 0]
 [2 4 4]]
[[2 9 0]
 [8 4 0]
 [2 4 4]]
